### ISSUE TITLE
Update Links in README

### ISSUE THREAD

**Issue by Abhinav-ark** [CSE-25/winter-of-code-s1#2]
- [ ] Update Latest Project Links in README
- [ ]  REMOVE TaskShogun - CLI Kanban Board from repos.

**Comment by SaranDharshanSP** [comment]
I am very interested to do this Issue. Please assign me this issue.
@Abhinav-ark @IAmRiteshKoushik @Ashrockzzz2003.

**Comment by Ajey95** [comment]
Im very interested !

**Comment by Abhinav-ark** [comment]
> Im very interested !

Unfortunately this issue is just for demonstration purposes. It is not a part of ACMWOC.
